# Generated by Django 4.0.3 on 2022-04-05 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0004_horario_producto_alter_persona_fechanac'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horario',
            name='entrada',
            field=models.DateField(blank=True, null=True, verbose_name='fechaentrada'),
        ),
        migrations.AlterField(
            model_name='horario',
            name='salida',
            field=models.DateField(blank=True, null=True, verbose_name='fechasalida'),
        ),
    ]
