# Generated by Django 4.0.3 on 2022-04-06 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0005_alter_horario_entrada_alter_horario_salida'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horario',
            name='entrada',
            field=models.IntegerField(verbose_name='entrada'),
        ),
        migrations.AlterField(
            model_name='horario',
            name='salida',
            field=models.IntegerField(verbose_name='salida'),
        ),
    ]
